# Manage Jenkins >> Credentials
credentials:

  # System (Store)
  system:
    domainCredentials:

    # Global credentials (unrestricted)
    - credentials:
      - string:
          description: "Example secret text credential"
          id: "example-secret-text"
          scope: GLOBAL
          secret: "change-me-secret-value"

      - usernamePassword:
          description: "Example username/password credential"
          id: "example-username-password"
          password: "change-me-password"
          scope: GLOBAL
          username: "change-me-username"

      - basicSSHUserPrivateKey:
          description: "Example SSH private key credential"
          id: "example-ssh-key"
          privateKeySource:
            directEntry:
              privateKey: |
                -----BEGIN OPENSSH PRIVATE KEY-----
                # Replace with your actual SSH private key
                # This is a placeholder - add your real key here
                -----END OPENSSH PRIVATE KEY-----
          scope: GLOBAL
          username: "ssh-user"
